//! Runs the Lab heuristics over `fixtures/*.md` and writes `out/`.
//!
//!   cargo run --manifest-path research/lab-heuristics/Cargo.toml
//!
//! Output: `out/report.md` (tables, weakest sentences, span lists),
//! `out/<fixture>-<pct>.md` (full ~~faded~~ renders), `out/thesaurus.json`.

use lab_heuristics::*;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let lists = Lists::load(&root.join("kg"));

    // Ad-hoc mode: `cargo run -- file.md ...` prints the table only.
    let extra: Vec<String> = std::env::args().skip(1).collect();
    if !extra.is_empty() {
        println!("| File | Words | Level | Target | Achieved | Delta (pp) |\n|---|---:|---|---:|---:|---:|");
        for f in extra {
            let doc = Doc::parse(&fs::read_to_string(&f).expect("read file"));
            let res = trim(&doc, &lists);
            for lv in &res.levels {
                println!(
                    "| {} | {} | {} | {:.0}% | {:.1}% | {:+.1} |",
                    Path::new(&f).file_name().unwrap().to_string_lossy(),
                    res.total_words,
                    lv.label,
                    lv.target_pct,
                    lv.achieved_pct,
                    lv.achieved_pct - lv.target_pct
                );
            }
        }
        return;
    }
    let out_dir = root.join("out");
    fs::create_dir_all(&out_dir).expect("create out/");

    fs::write(
        out_dir.join("thesaurus.json"),
        thesaurus_json("Lab heuristics", &lists.thesaurus_terms()),
    )
    .unwrap();

    let mut fixtures: Vec<PathBuf> = fs::read_dir(root.join("fixtures"))
        .expect("fixtures/")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().map(|x| x == "md").unwrap_or(false))
        .collect();
    fixtures.sort();

    let mut table = String::from(
        "| Fixture | Words | Level | Target | Target words | Cut words | Achieved | Delta (pp) | Within +/-3pp |\n|---|---:|---|---:|---:|---:|---:|---:|---|\n",
    );
    let mut detail = String::new();
    let mut all_ok = true;
    let mut ablation = String::from(
        "| Fixture | Level | Recommended (all granularities + fit) | Sentences only + fit | Naive rank prefix (no fit) |\n|---|---|---:|---:|---:|\n",
    );

    for path in &fixtures {
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        let raw = fs::read_to_string(path).unwrap();
        let doc = Doc::parse(&raw);
        let res = trim(&doc, &lists);
        let scores = score_sentences(&doc, &lists);
        let sent_only = trim_filtered(&doc, &lists, |c| c.granularity == Granularity::Sentence);
        let naive = naive_prefix(&doc, &lists);
        for (li, lv) in res.levels.iter().enumerate() {
            let _ = writeln!(
                ablation,
                "| {} | {} | {:+.1}pp | {:+.1}pp | {:+.1}pp |",
                stem,
                lv.label,
                lv.achieved_pct - lv.target_pct,
                sent_only.levels[li].achieved_pct - lv.target_pct,
                naive[li] - lv.target_pct
            );
        }

        for lv in &res.levels {
            let delta = lv.achieved_pct - lv.target_pct;
            let ok = delta.abs() <= 3.0;
            all_ok &= ok;
            let _ = writeln!(
                table,
                "| {} | {} | {} | {:.0}% | {} | {} | {:.1}% | {:+.1} | {} |",
                stem,
                res.total_words,
                lv.label,
                lv.target_pct,
                lv.target_words,
                lv.cut_words,
                lv.achieved_pct,
                delta,
                if ok { "yes" } else { "NO" }
            );
            let ranges = merged_ranges(&res.candidates, &lv.selected);
            let render = render_strike(&doc.text, &ranges);
            let header = format!(
                "<!-- generated by research/lab-heuristics; do not edit -->\n# {} at {} (~{:.0}%)\n\n{} -> {} words, -{:.1}%\n\n",
                stem,
                lv.label,
                lv.target_pct,
                res.total_words,
                res.total_words - lv.cut_words,
                lv.achieved_pct
            );
            fs::write(
                out_dir.join(format!("{}-{:02.0}.md", stem, lv.target_pct)),
                header + &render + "\n",
            )
            .unwrap();
        }

        // ---- per-fixture detail
        let _ = writeln!(detail, "\n## {}\n", stem);
        let _ = writeln!(
            detail,
            "{} words, {} sentences, {} trim candidates.\n",
            res.total_words,
            doc.sentences.len(),
            res.candidates.len()
        );
        let hits = lists.style.find(&doc.text);
        let count = |c: &str| hits.iter().filter(|h| h.concept == c).count();
        let _ = writeln!(
            detail,
            "Mark hits: filler {}, hedge {}, hedge-phrase {}, tone {}.\n",
            count("lab-filler"),
            count("lab-hedge"),
            count("lab-hedge-phrase"),
            count(TONE)
        );
        let ranked = rank_weakest(&scores);
        let k = weakest_count(scores.len());
        let _ = writeln!(
            detail,
            "### Weakest sentences (top {} of {} marked)\n",
            k,
            scores.len()
        );
        let _ = writeln!(detail, "| Rank | Weakness | Hedge/filler | Centrality | Redundancy | Function | KG | Sentence |\n|---:|---:|---:|---:|---:|---:|---:|---|");
        for (r, &si) in ranked.iter().take(k).enumerate() {
            let s = &scores[si];
            let _ = writeln!(
                detail,
                "| {} | {:.3} | {:.2} | {:.2} | {:.2} | {:.2} | {:.1} | {} |",
                r + 1,
                s.weakness,
                s.hedge_filler,
                s.centrality,
                s.redundancy,
                s.function_ratio,
                s.kg_coverage,
                short(doc.sentence_text(si), 110)
            );
        }
        let _ = writeln!(detail, "\n### Spans by first level (document order)\n");
        let _ = writeln!(
            detail,
            "| Level | Granularity | Words | Reason | Span |\n|---|---|---:|---|---|"
        );
        let mut order: Vec<usize> = (0..res.candidates.len())
            .filter(|&i| res.level_of[i].is_some())
            .collect();
        order.sort_by_key(|&i| (res.level_of[i], res.candidates[i].start));
        for i in order {
            let c = &res.candidates[i];
            let _ = writeln!(
                detail,
                "| {} | {:?} | {} | {} | {} |",
                LEVELS[res.level_of[i].unwrap()].0,
                c.granularity,
                doc.words_in(c.start, c.end).len(),
                c.reason,
                short(doc.text[c.start..c.end].trim(), 90)
            );
        }
    }

    let report = format!(
        "<!-- generated by research/lab-heuristics; do not edit -->\n# Lab heuristics prototype report\n\n## Target vs achieved\n\n{}\nAll levels within +/-3pp: {}\n\n## Ablation (delta from target)\n\n{}{}",
        table,
        if all_ok { "yes" } else { "NO" },
        ablation,
        detail
    );
    fs::write(out_dir.join("report.md"), &report).unwrap();
    print!("{}", table);
    println!(
        "\nAll levels within +/-3pp: {}",
        if all_ok { "yes" } else { "NO" }
    );
    println!("Wrote {}", rel(&out_dir, &root));
}

fn short(s: &str, n: usize) -> String {
    let s = s.replace('|', "\\|");
    if s.chars().count() <= n {
        s
    } else {
        let mut t: String = s.chars().take(n).collect();
        t.push_str("...");
        t
    }
}

fn rel(p: &Path, root: &Path) -> String {
    p.strip_prefix(root)
        .map(|x| x.display().to_string())
        .unwrap_or_else(|_| p.display().to_string())
}
